CREATE TABLE wedding_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_key VARCHAR(64) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(500),
    couple_names VARCHAR(255),
    body TEXT,
    event_date VARCHAR(255),
    venue VARCHAR(500),
    extra_copy TEXT,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO wedding_content (page_key, title, subtitle, couple_names, body, event_date, venue, extra_copy, updated_at)
VALUES (
    'home',
    'Two families, one mandap',
    'With the blessings of our elders, we invite you to celebrate with us.',
    'Poojan & Partner',
    'Our families are overjoyed to share this season of ceremonies. This page will gather dates, venues, and the quiet details that make an Indian wedding feel like home — marigold, music, and the people we love.',
    'Dates to be announced',
    'India',
    'Please keep this site bookmarked. Roka details are posted, and later ceremonies will appear here when the time is right.',
    CURRENT_TIMESTAMP
);

INSERT INTO wedding_content (page_key, title, subtitle, couple_names, body, event_date, venue, extra_copy, updated_at)
VALUES (
    'roka',
    'Roka',
    'The families meet, blessings are exchanged, and a promise is spoken.',
    'Poojan & Partner',
    'Roka marks the formal coming-together of both families — a warm gathering of elders, sweets, and the first public joy of the wedding season. We would be honoured by your presence and your aashirwad.',
    'To be announced',
    'Venue to be announced',
    'Dress code: festive Indian attire. Kindly share any dietary notes with the family. A fuller invitation will follow for later ceremonies.',
    CURRENT_TIMESTAMP
);
